name = "PowerSystemExtensions"
uuid = "998307d2-be9b-4dab-b420-81c4bd3dbd26"
authors = ["sourabhdalvi <sourabh.p.dalvi@gmail.com>"]
version = "0.1.0"

[deps]
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
